#!/bin/bash

case "$1" in
	drop)
		if [ -n "$2" ]; then
			rm ./"$2".* || true
			exit 0
		fi
	;;

	keep)
		if [ -n "$2" ] && [ -n "$3" ] && ( echo "$2" | grep -q "^[0-9]*$" ); then
			for f in ./"$3".{start,run,stop}; do
				if [ -e "$f" ]; then
					btime="$(stat --format %W "$f")"
					ctime="$(stat --format %Z "$f")"
					t=
					if [ "$btime" != "-" ]; then
						t=$btime
					else
						t=$ctime
					fi
					suf="$(date --date="@$btime" '+.%s.%Y-%m-%d.%H-%M-%S')"
					mv "$f" "$f$suf" || true
				fi
			done

			dropbefore=$(($(date +%s) - $2 * 86400))
			for f in ./"$3".*; do
				btime="$(stat --format %W "$f")"
				ctime="$(stat --format %Z "$f")"
				if [ "$btime" != "-" ]; then
					test "$btime" -gt "$dropbefore" || rm "$f" || true
				else
					test "$ctime" -gt "$dropbefore" || rm "$f" || true
				fi
			done
			exit 0
		fi
	;;
esac

echo "Usage:"
echo " $0 drop <stem>         Delete previous logs without keeping copies."
echo " $0 keep <days> <stem>  Timestamp old logs, delete if older than given amount of days."
exit 1
